# This is a basic workflow to help you get started with Actions

name: HEROKU DEPLOYMENT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Criando build do Eureka Server
        run: mvn -B package --file configserver/pom.xml -DskipTests && mkdir builds && cp configserver/target/*.jar builds
      - name: Criando build do Service Discovery Server
        run: mvn -B package --file servicediscovery/pom.xml -DskipTests && cp servicediscovery/target/*.jar builds
      - name: Criando build do API Gateway Server
        run: mvn -B package --file apigateway/pom.xml -DskipTests && cp apigateway/target/*.jar builds
      - name: Criando build do Account Service
        run: mvn -B package --file accounts/pom.xml -DskipTests && cp accounts/target/*.jar builds
      - name: Criando build do Inventories Service
        run: mvn -B package --file inventories/pom.xml -DskipTests && cp inventories/target/*.jar builds
      - name: Criando build do Orders Service
        run: mvn -B package --file orders/pom.xml -DskipTests && cp orders/target/*.jar builds
      - name: Criando build do Recommendations Service
        run: mvn -B package --file recommendations/pom.xml -DskipTests && cp recommendations/target/*.jar builds
      - name: Criando build do Shippings Service
        run: mvn -B package --file shippings/pom.xml -DskipTests && cp shippings/target/*.jar builds
      - name: Upload math result for job
        uses: actions/upload-artifact@v1
        with:
          name: Fazendo upload dos arquivos de build
          path: builds
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Deploy do Config Server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-configserver
        run: heroku plugins:install java && heroku deploy:jar builds/configserver-0.0.1-SNAPSHOT.jar --app dsi-spring-configserver
      - name: Deploy do Service Discovery Server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-servicediscovery
        run: heroku deploy:jar builds/servicediscovery-0.0.1-SNAPSHOT.jar --app dsi-spring-servicediscovery
      - name: Deploy do API Gateway Server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-apigateway
        run: heroku deploy:jar builds/apigateway-0.0.1-SNAPSHOT.jar --app dsi-spring-apigateway
      - name: Deploy do Account Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-accounts
        run: heroku deploy:jar builds/accounts-0.0.1-SNAPSHOT.jar --app dsi-spring-accounts
      - name: Login to Heroku Container registry 2
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_2 }}
        run: heroku container:login
      - name: Deploy do Recommendations Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_2 }}
          HEROKU_APP_NAME: dsi-spring-recommendations
        run: heroku deploy:jar builds/recommendations-0.0.1-SNAPSHOT.jar --app dsi-spring-recommendations
      - name: Deploy do Orders Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_2 }}
          HEROKU_APP_NAME: dsi-spring-orders
        run: heroku deploy:jar builds/orders-0.0.1-SNAPSHOT.jar --app dsi-spring-orders
      - name: Deploy do Inventories Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_2 }}
          HEROKU_APP_NAME: dsi-spring-inventories
        run: heroku deploy:jar builds/inventories-0.0.1-SNAPSHOT.jar --app dsi-spring-inventories
      - name: Deploy do Shippings Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_2 }}
          HEROKU_APP_NAME: dsi-spring-shippings
        run: heroku deploy:jar builds/shippings-0.0.1-SNAPSHOT.jar --app dsi-spring-shippings
