# This is a basic workflow to help you get started with Actions

name: CI FOR PROD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Config Server
        run: mvn -B package --file configserver/pom.xml
      - name: Criando o caminho para armazenar as builds
        run: mkdir builds && cp configserver/target/*.jar builds
      - name: Build Service Discovery Server
        run: mvn -B package --file servicediscovery/pom.xml
      - name: Adicionando o servicediscovery ao builds
        run: cp servicediscovery/target/*.jar builds
      - name: Build Api Gateway Server
        run: mvn -B package --file apigateway/pom.xml
      - name: Adicionando o Api Gateway ao builds
        run: cp apigateway/target/*.jar builds
      - name: Build Accounts Service
        run: mvn -B package --file apigateway/pom.xml
      - name: Adicionando o Accounts Service ao builds
        run: cp accounts/target/*.jar builds
      - name: Upload math result for job
        uses: actions/upload-artifact@v1
        with:
          name: Fazendo upload dos arquivos de build
          path: builds
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push config server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-configserver
        run: heroku plugins:install java && heroku deploy:jar builds/configserver-0.0.1-SNAPSHOT.jar --app dsi-spring-configserver
      - name: Build and push service discovery
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-servicediscovery
        run: heroku deploy:jar builds/servicediscovery-0.0.1-SNAPSHOT.jar --app dsi-spring-servicediscovery
      - name: Build and push Api Gateway server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-apigateway
        run: heroku deploy:jar builds/apigateway-0.0.1-SNAPSHOT.jar --app dsi-spring-apigateway
      - name: Build and push Accounts Service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: dsi-spring-accounts
        run: heroku deploy:jar builds/accounts-0.0.1-SNAPSHOT.jar --app dsi-spring-accounts
